name: Publish to Docker Hub

on:
  push:
    branches:
      - master
      - develop

jobs:
  publish-to-docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "BRANCH: ${BRANCH}"
          DOCKER_TAGS="${BRANCH},latest"
          echo "::set-env name=DOCKER_TAGS::$DOCKER_TAGS"

      - name: Publish Docker Github Action
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: unfoldingword/dcs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: ${{ env.DOCKER_TAGS }}
